[package]
name = "portfolio"
version = "0.1.0"
authors = ["ZennDev1337 <zenndev@protonmail.com>"]
edition = "2021"


[dependencies]
gloo-timers = "0.3.0"
wasm-bindgen = "0.2.87"
yew = { version = "0.20.0", features = ["csr"] }
