[package]
name = "portfolio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-timers = "0.3.0"
wasm-bindgen = "0.2.87"
yew = { version = "0.20.0", features = ["csr"] }
